// Curriculum generator (T2). Turns a business profile + intake dump + research
// into the core training program: a company-intro module, one module per role,
// operations modules from the intake, and a weekly onboarding schedule.
//
// Each module's markdown is generated by Claude with a cached system prefix
// (business profile + intake + research context) so the per-module calls reuse
// it. Runs fully offline on the mock LLM. Compliance modules are added
// separately by lib/agents/compliance.ts; the orchestrator merges both.

import { nanoid } from 'nanoid';
import { getLlm } from '../contracts/llm';
import type {
  BusinessRole,
  IntakeProfile,
  OnboardingWeek,
  Quiz,
  ResearchArtifact,
  TrainingModule,
  TrainingModuleType,
} from '../../types/index';

export interface CurriculumBusiness {
  name: string;
  industry: string;
  state: string;
  mission?: string;
  roles: BusinessRole[];
}

export interface CurriculumInput {
  businessId: string;
  programId: string;
  programVersion: number;
  business: CurriculumBusiness;
  intake?: IntakeProfile;
  /** Industry-standard / competitor research (compliance artifacts handled elsewhere). */
  research?: ResearchArtifact[];
  /** Module `order` offset (default 1). */
  startOrder?: number;
}

export interface CurriculumResult {
  modules: TrainingModule[];
  scheduleWeeks: OnboardingWeek[];
}

/** Matches `trainingProgramSchema` DoD: assembled programs need ≥2 role modules. */
export function curriculumMeetsRoleDoD(result: CurriculumResult): boolean {
  return result.modules.filter((m) => m.type === 'role_specific').length >= 2;
}

interface ModulePlan {
  type: TrainingModuleType;
  title: string;
  keyPoints: string[];
  roleId?: string;
  /** Keywords to attach matching research artifacts as provenance. */
  match: RegExp;
  /** Equipment sim to attach to the generated module (e.g. 'sim_boba_station'). */
  simId?: string;
}

// ---------------------------------------------------------------------------
// Plan the modules from the business + intake.
// ---------------------------------------------------------------------------

/** DoD gate: assembled programs need ≥2 role_specific modules. */
function ensureMinimumRoleModules(
  plan: ModulePlan[],
  business: CurriculumBusiness,
): void {
  const roleSpecific = plan.filter((p) => p.type === 'role_specific');
  const needed = 2 - roleSpecific.length;
  if (needed <= 0) return;

  const namedRoles = business.roles.filter((r) => r.title.trim());

  if (namedRoles.length === 0) {
    plan.push(
      {
        type: 'role_specific',
        title: 'Front of House: Role Essentials',
        keyPoints: [
          'greeting guests and taking orders accurately',
          'handoffs between front and back of house',
          'keeping the customer area clean and welcoming',
        ],
        match: /front|customer|cashier|guest|order/i,
      },
      {
        type: 'role_specific',
        title: 'Production: Role Essentials',
        keyPoints: [
          'following recipes and build standards every time',
          'food safety and quality checks during prep',
          'communicating delays or outages to the team',
        ],
        match: /production|barista|prep|recipe|quality/i,
      },
    );
    return;
  }

  const role = namedRoles[0];
  for (let i = 0; i < needed; i++) {
    const supplement =
      i === 0 && roleSpecific.length === 1
        ? role.customerFacing
          ? {
              title: `${role.title}: Customer Interactions`,
              keyPoints: [
                'handling common customer questions and special requests',
                'recovering calmly when something goes wrong',
                'when to call a shift lead or manager',
              ],
            }
          : {
              title: `${role.title}: Team Coordination`,
              keyPoints: [
                'how this role supports other stations during rush',
                'quality checks before items go out',
                'clear communication with front-of-house staff',
              ],
            }
        : {
            title: `${role.title}: On-the-Job Scenarios`,
            keyPoints: [
              'what to do during a busy rush',
              'common mistakes and how to avoid them',
              'who to ask when something is unclear',
            ],
          };

    plan.push({
      type: 'role_specific',
      roleId: role.id,
      title: supplement.title,
      keyPoints: supplement.keyPoints,
      match: new RegExp(role.title.replace(/[^a-z0-9]+/gi, '.?'), 'i'),
    });
  }
}

function planModules(input: CurriculumInput): ModulePlan[] {
  const { business, intake } = input;
  const plan: ModulePlan[] = [];

  plan.push({
    type: 'company_intro',
    title: `Welcome to ${business.name}`,
    keyPoints: [
      'the company mission and values',
      'who does what (the roles on the team)',
      'the tone we set with customers and each other',
    ],
    match: /intro|welcome|mission|values|onboard/i,
  });

  for (const role of business.roles) {
    if (!role.title.trim()) continue;
    plan.push({
      type: 'role_specific',
      roleId: role.id,
      title: `${role.title}: Role Essentials`,
      keyPoints: [
        `the core responsibilities of a ${role.title}`,
        role.description || 'day-to-day duties and standards',
        role.customerFacing
          ? 'how to handle customers warmly and correctly'
          : 'how this role supports the rest of the team',
      ],
      match: new RegExp(role.title.replace(/[^a-z0-9]+/gi, '.?'), 'i'),
    });
  }

  ensureMinimumRoleModules(plan, business);

  if (intake?.openingClosing) {
    plan.push({
      type: 'operations',
      title: 'Operations: Opening & Closing',
      keyPoints: [
        'the opening checklist and what must be ready before service',
        'the closing checklist, cash drop, and lock-up',
        'why each step matters',
      ],
      match: /open|clos|checklist|shift/i,
    });
  }
  if (intake?.cleaning) {
    plan.push({
      type: 'operations',
      title: 'Operations: Cleaning & Sanitation',
      keyPoints: [
        'the cleaning schedule and stations',
        'sanitizer use and temperature/hygiene logs',
        'why cleanliness protects customers and the team',
      ],
      match: /clean|saniti|hygiene|temp/i,
    });
  }
  if (intake?.machineOperations) {
    plan.push({
      type: 'operations',
      title: 'Operations: Equipment & Machines',
      keyPoints: [
        'how to operate each machine safely',
        'routine calibration and maintenance',
        'what to do when something breaks',
      ],
      match: /machine|equipment|sealer|blender|brewer|calibrat/i,
      simId: 'sim_boba_station',
    });
  }
  if (intake?.directContext) {
    plan.push({
      type: 'operations',
      title: 'Operations: From Your Documents',
      keyPoints: [
        'standards and procedures from owner-uploaded materials',
        'how daily work matches handbooks and SOPs you provided',
        'where to double-check when something is not covered in training',
      ],
      match: /document|handbook|upload|sop|pdf|google/i,
    });
  }
  if (intake?.drinkProduction || (intake?.recipes && intake.recipes.length > 0)) {
    const recipeNames = (intake?.recipes ?? []).map((r) => r.name);
    plan.push({
      type: 'operations',
      title: 'Operations: Production & Recipes',
      keyPoints: [
        'the standard build/production order',
        recipeNames.length
          ? `our signature recipes: ${recipeNames.join(', ')}`
          : 'our signature recipes and ratios',
        'how to confirm options and keep quality consistent',
      ],
      match: /recipe|production|drink|build|ratio/i,
    });
  }

  // Guarantee at least one operations module even with no intake.
  if (!plan.some((p) => p.type === 'operations')) {
    plan.push({
      type: 'operations',
      title: 'Operations: Daily Standards',
      keyPoints: [
        'the daily workflow from open to close',
        'quality and cleanliness standards',
        'who to ask when unsure',
      ],
      match: /operation|daily|workflow|standard/i,
    });
  }

  return plan;
}

// ---------------------------------------------------------------------------
// LLM context + helpers.
// ---------------------------------------------------------------------------

function curriculumSystem(input: CurriculumInput): string {
  const { business, intake } = input;
  const research = (input.research ?? []).filter(
    (a) => a.category !== 'compliance',
  );
  const researchCtx = research.length
    ? research.map((a) => `- ${a.title} (${a.source}): ${a.summary}`).join('\n')
    : '- (no external research provided)';

  const intakeLines: string[] = [];
  if (intake?.openingClosing) intakeLines.push(`Opening/closing: ${intake.openingClosing}`);
  if (intake?.cleaning) intakeLines.push(`Cleaning: ${intake.cleaning}`);
  if (intake?.machineOperations) intakeLines.push(`Machines: ${intake.machineOperations}`);
  if (intake?.drinkProduction) intakeLines.push(`Production: ${intake.drinkProduction}`);
  if (intake?.recipes?.length) {
    intakeLines.push(
      `Recipes:\n${intake.recipes
        .map((r) => `  • ${r.name}: ${r.ingredients.join(', ')} | steps: ${r.steps.join(' → ')}`)
        .join('\n')}`,
    );
  }
  if (intake?.notes) intakeLines.push(`Owner notes: ${intake.notes}`);
  if (intake?.directContext) {
    intakeLines.push(
      `Uploaded documents & links (parsed):\n${intake.directContext.slice(0, 12_000)}`,
    );
  }

  return [
    'You are an employee-training author for small, often immigrant-owned businesses.',
    'Write clear, warm, practical training modules a new hire can follow on their first shifts.',
    'Ground every module in the owner-provided operations below — use their real recipes, steps, and standards, not generic filler.',
    '',
    `Business: ${business.name} — ${business.industry} in ${business.state || 'US'}.`,
    business.mission ? `Mission: ${business.mission}` : '',
    `Roles: ${business.roles.map((r) => `${r.title}${r.customerFacing ? ' (customer-facing)' : ''}`).join(', ') || '—'}`,
    '',
    'Owner operations dump:',
    intakeLines.length ? intakeLines.join('\n') : '- (none provided)',
    '',
    'Research context (industry standards / competitor benchmarks):',
    researchCtx,
    '',
    'Output ONLY the module body as GitHub-flavored Markdown, starting with an H1 title.',
    'Keep it ~250–450 words with short sections and a final "Key points" list. No preamble, no quiz.',
  ]
    .filter((l) => l !== '')
    .join('\n');
}

function fallbackMarkdown(plan: ModulePlan): string {
  return [
    `# ${plan.title}`,
    '',
    'This module covers what you need for this part of the job.',
    '',
    '## Key points',
    ...plan.keyPoints.map((p) => `- ${p[0].toUpperCase()}${p.slice(1)}.`),
  ].join('\n');
}

function buildQuiz(moduleId: string, plan: ModulePlan): Quiz {
  return {
    id: `quiz_${moduleId}`,
    moduleId,
    questions: [
      {
        id: 'q1',
        prompt: `What are the most important things to remember from "${plan.title}"?`,
        type: 'free_response',
        rubric: `Full credit: the answer reflects the key points — ${plan.keyPoints.join('; ')}.`,
      },
    ],
  };
}

function artifactIdsFor(plan: ModulePlan, research: ResearchArtifact[]): string[] {
  return research
    .filter((a) => plan.match.test(`${a.title} ${a.summary}`))
    .map((a) => a.id);
}

function chunk<T>(arr: T[], size: number): T[][] {
  const out: T[][] = [];
  for (let i = 0; i < arr.length; i += size) out.push(arr.slice(i, i + size));
  return out;
}

// ---------------------------------------------------------------------------
// Main entry point.
// ---------------------------------------------------------------------------

export async function generateCurriculum(
  input: CurriculumInput,
): Promise<CurriculumResult> {
  const plans = planModules(input);
  const research = input.research ?? [];
  const llm = getLlm();
  const system = curriculumSystem(input);
  const startOrder = input.startOrder ?? 1;

  const modules = await Promise.all(
    plans.map(async (plan, i) => {
      const moduleId = `mod_${nanoid(8)}`;
      let contentMarkdown: string;
      try {
        const out = (
          await llm.generate({
            system,
            cache: true,
            maxTokens: 1800,
            messages: [
              {
                role: 'user',
                content: `Write the training module titled "${plan.title}" (${plan.type}). Cover: ${plan.keyPoints.join('; ')}.`,
              },
            ],
          })
        ).trim();
        contentMarkdown = out || fallbackMarkdown(plan);
      } catch (err) {
        console.error(`[curriculum] generation failed for "${plan.title}":`, err);
        contentMarkdown = fallbackMarkdown(plan);
      }

      const mod: TrainingModule = {
        id: moduleId,
        programId: input.programId,
        order: startOrder + i,
        type: plan.type,
        title: plan.title,
        contentMarkdown,
        quiz: buildQuiz(moduleId, plan),
        sourceArtifactIds: artifactIdsFor(plan, research),
      };
      if (plan.roleId) mod.roleId = plan.roleId;
      if (plan.simId) mod.simId = plan.simId;
      return mod;
    }),
  );

  // Weekly schedule: split the curriculum modules across ~3 weeks.
  const perWeek = Math.max(1, Math.ceil(modules.length / 3));
  const scheduleWeeks: OnboardingWeek[] = chunk(modules, perWeek).map(
    (group, i) => ({
      week: i + 1,
      goals: group.map((m) => `Complete "${m.title}"`),
      moduleIds: group.map((m) => m.id),
    }),
  );

  return { modules, scheduleWeeks };
}
